# -*- coding: utf-8 -*-
"""preprocessing_functions.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-k-jEFqfNgEFLaw1TeKpxf-ROlpLjb0
"""

import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OrdinalEncoder
from scipy.stats import mstats
import numpy as np

def handle_missing_values(df):
    df.fillna(0, inplace=True)
    return df

def convert_date_column(df):
    df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%y')
    return df

def encode_categorical_feature(df):
    encoder = OrdinalEncoder()
    df['grade'] = encoder.fit_transform(df[['grade']])
    return df

def map_values(df):
    mapping_emp_length = {
        '< 1 year': 0,
        '1 year': 1,
        '2 years': 2,
        '3 years': 3,
        '4 years': 4,
        '5 years': 5,
        '6 years': 6,
        '7 years': 7,
        '8 years': 8,
        '9 years': 9,
        '10+ years': 10
    }
    df['emp_length'] = df['emp_length'].map(mapping_emp_length)

    mapping_term = {
        ' 60 months': 60,
        ' 36 months': 36
    }
    df['term'] = df['term'].map(mapping_term)
    return df

def drop_null_rows(df):
    df.dropna(subset=['pub_rec_bankruptcies', 'revol_util', 'title'], inplace=True)
    return df

def impute_missing_values(df):
    columns = ["num_actv_bc_tl", "mort_acc", "tot_cur_bal", "emp_length"]
    imputer = KNNImputer(n_neighbors=5)
    df[columns] = imputer.fit_transform(df[columns])
    return df

def winsorize_column(df):
    column_to_winsorize = 'annual_inc'
    winsorized_data = mstats.winsorize(df[column_to_winsorize], limits=[0.01, 0.01])
    df[column_to_winsorize] = winsorized_data
    return df

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

# Define the preprocessing pipeline
preprocessing_pipeline = Pipeline([
    ('handle_missing_values', FunctionTransformer(handle_missing_values)),
    ('convert_date_column', FunctionTransformer(convert_date_column)),
    ('encode_categorical_feature', FunctionTransformer(encode_categorical_feature)),
    ('map_values', FunctionTransformer(map_values)),
    ('drop_null_rows', FunctionTransformer(drop_null_rows)),
    ('impute_missing_values', FunctionTransformer(impute_missing_values)),
    ('winsorize_column', FunctionTransformer(winsorize_column))
])

# Save the preprocessing pipeline as a pickle file
import joblib
joblib.dump(preprocessing_pipeline, 'preprocessing_pipeline.pkl')

